Fix variable shadowing bug in vowel layout examples
Changed map parameter from 't' to 'token' to avoid shadowing the
translation function 't' from useLocalization. This was causing a
'TypeError: t2 is not a function' error when trying to translate
meaning text in the examples.